# Generated by Django 3.2 on 2021-04-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_mypost_uploaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=50)),
                ('phone_no', models.CharField(max_length=15)),
                ('msg', models.TextField(max_length=5000)),
            ],
        ),
    ]
