# Generated by Django 3.2 on 2021-04-18 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='Cemail',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='Cname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone_no',
            new_name='Cphone_no',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='msg',
            new_name='massage',
        ),
    ]
