# Generated by Django 3.2 on 2021-04-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20210418_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='massage',
            new_name='Cmassage',
        ),
    ]
