# Generated by Django 3.2 on 2021-04-19 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_rename_massage_contact_cmassage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactinfo',
        ),
    ]
