# Generated by Django 3.2 on 2021-04-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_rename_contact_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='Cmassage',
            field=models.CharField(max_length=5000),
        ),
    ]
